apiVersion: apps/v1
kind: Deployment
metadata:
  name: amori-backend  # <--- 'hello-world-deployment'에서 수정
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amori-backend # <--- 'hello-world'에서 수정
  template:
    metadata:
      labels:
        app: amori-backend # <--- 'hello-world'에서 수정
    spec:
      containers:
      - name: amori-backend-container # (이름은 자유)
        image: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/amori-docker-images/amori-backend:latest
        ports:
        - containerPort: 8080