apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amori-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: amori-backend-service
            port:
              number: 80