apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amori-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: amori-backend-service
            port:
              number: 80